### ISSUE TITLE
remove_first/last leaves dangling parent() id

### ISSUE THREAD

**Issue by spearman** [iwburns/slab-tree#14]
Here's a small program showing the issue:

```
use slab_tree::TreeBuilder;
fn main() {
    let mut tree = TreeBuilder::new().with_root(0i64).build();
    let root_id = tree.root().unwrap().node_id();
    let one_id = tree.get_mut(root_id).unwrap().append(1).node_id();
    let two_id = tree.get_mut(one_id).unwrap().append(2).node_id();
    tree.root_mut().unwrap().remove_first();
    assert!(tree.get(one_id).is_none());
    let two = tree.get(two_id).unwrap();
    assert!(two.parent().is_none()); // panic
}
```

I think the intended behavior here is to orphan the children, so I expected the parent() field to be None.

**Comment by iwburns** [comment]
There's definitely some cleanup that needs to be done here, but I'm actually not sure what the solution should be.

I can see people wanting different things in different situations, but I'm not really sure how to accommodate that.  In `id_tree` I provided a "behavior" enum that you have to specify; I guess that could be done here as well, but I always had mixed feelings about that implementation.

Do you have any thoughts here?

**Comment by spearman** [comment]
The behavior enum seems fine. The only downside I can think of is that it's another type in the interface, but otherwise you would probably need specially named functions for each case.
